pipeline {
    agent any
    environment {
        DOCKER_HUB_REPO = 'akshaykomath/node-webapp'
        DOCKER_HUB_CREDENTIALS = '5708d687-8960-4e7e-856c-e53a7724aabb' // Jenkins credentials ID
        DOCKER_IMAGE = "${DOCKER_HUB_REPO}:${env.BUILD_ID}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/akshaykomath15/gitnew.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm test'
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    dockerImage = docker.build(DOCKER_IMAGE)
                }
            }
        }
        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }
}
