apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-webapp
  template:
    metadata:
      labels:
        app: node-webapp
    spec:
      containers:
      - name: node-webapp
        image: akshaykomath1/test-webapp:latest
        ports:
        - containerPort: 3000
