apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webapp-deployment
  labels:
    app: test-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-webapp
  template:
    metadata:
      labels:
        app: test-webapp
    spec:
      containers:
      - name: test-webapp
        image: akshaykomath1/test-webapp:latest
        ports:
        - containerPort: 80
